### ISSUE TITLE
List implementation

### ISSUE THREAD

**Issue by stawicki91** [mgdabrowska/study#5]
Stwórz dwie klasy List i ListTest,
klasa List powinna zawierać pole int[] i metody
int get(int index) - zwraca liczbe na miejscu index
int size() - zwraca ilosc wszystkich elementow w tablicy
void remove(int index)- usuwa element z miejsca index
void add(int element) - dodaje element na koniec listy
void addAt(int index, int element) - dodaje element w miejsce index
void change(int index, int element) - zmienia element w miejscu index

Klasa ma za zadanie zastąpić zwykłe tablice, klasa ListTest powinna testować klasę List, np w metodzie main:

```
List list = new List();
list.add(1);
list.add(3);
list.add(6);
list.addAt(1, 2);
list.change(3, 4);
for(int i=0; i<list.size(); i++) {
   System.out.println(list.get(i)+" ");
}
//do tego miejsca powinna wypisac 1 2 3 4

list.remove(3);
list.remove(0);
for(int i=0; i<list.size(); i++) {
   System.out.println(list.get(i)+" ");
}
//w tym miejscu powinna wypisac 2 3

list.remove(0);
list.remove(0);
System.out.println(list.size());
//w tym miejscu powinno wypisać 0
```

**Comment by stawny** [comment]
chyba mozemy to zamknac
